services:
  - type: web
    name: boringlife
    env: docker
    region: ohio
    plan: free # Can be updated based on Render user tier
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: DEVELOPMENT_MODE
        value: "false"
      - key: DB_HOST
        value: mysql-16fe8592-ianshakes16-0080.b.aivencloud.com
      - key: DB_PORT
        value: "10353"
      - key: DB_USER
        value: avnadmin
      - key: DB_NAME
        value: defaultdb
      - key: DB_PASS
        sync: false # Requires manual entry in the Render Dashboard upon deployment
      - key: DB_SSL
        value: "true"
