services:
  - type: web
    name: sidequest
    runtime: docker
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: DEVELOPMENT_MODE
        value: "false"
      - key: DB_HOST
        value: mysql-16fe8592-ianshakes16-0080.b.aivencloud.com
      - key: DB_PORT
        value: "10353"
      - key: DB_USER
        value: avnadmin
      - key: DB_NAME
        value: defaultdb
      - key: APP_URL
        value: https://mylifeisboring.onrender.com
      - key: ADMIN_URL_SECRET
        value: x9_admin_portal_hidden
      - key: SESSION_TIMEOUT
        value: "86400"
